version: '3.3'
services:
  skybud-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: skybud-webapp:latest
    container_name: skybud-webapp
    env_file:
      - .env
    restart: unless-stopped